#! /usr/bin/env sh

# todo
# todo dir
# todo init
# todo tasks
# todo times
# todo add <task>
# todo addproject <project>
# todo addtime <time>
# todo hide <task>
# todo rm <task>
# todo rmproject <project>
# todo rmtime <time>
# todo edit <task>
# todo assign <task> <time>
# todo unassign <task>
# todo mv <task> <project>


# Set up $EDITOR if needed

if [ -z "$EDITOR" ]; then
    EDITOR="nano"
fi

# Set up todo directory if needed

if [ -z "$TODODIR" ]; then
    TODODIR="$HOME/.todo"
fi

if [ -e "$TODODIR" ]; then
    if [ ! -d "$TODODIR" ]; then
        echo "$TODODIR is not a directory"
        exit 1
    fi
else
    mkdir -p "$TODODIR/tasks"
    mkdir -p "$TODODIR/times"
fi

# Process arguments

if [ "$#" -eq 0 ]; then

    for dir in "waiting" "today" "thisweek" "thismonth"; do
        dirpath="$TODODIR/times/$dir"
        if [ -d $dirpath ] && [ ! -z $(ls -A $dirpath) ]; then
            printf "\033[1m%s\033[m\n" $dir
            find $dirpath -type l -execdir realpath --relative-to="$TODODIR/tasks" '{}' +
            printf "\n"
        fi
    done

elif [ "$1" = "dir" ]; then

    echo $TODODIR

elif [ "$1" = "init" ]; then

    for dir in "waiting" "today" "thisweek" "thismonth" "someday"; do
        [ -e "$TODODIR/times/$dir" ] || mkdir "$TODODIR/times/$dir"
    done

elif [ "$1" = "tasks" ]; then

    tree $TODODIR/tasks

elif [ "$1" = "times" ]; then

    tree $TODODIR/times

elif [ "$1" = "add" ]; then

    taskpath="$TODODIR/tasks/$2"

    # Make sure $2 doesn't exist
    if [ -e $taskpath ]; then
        echo "'$2' already exists"
        exit 1
    fi

    touch $taskpath

elif [ "$1" = "addproject" ]; then

    projectpath="$TODODIR/tasks/$2"

    # Make sure $2 doesn't exist
    if [ -e $projectpath ]; then
        echo "'$2' already exists"
        exit 1
    fi

    mkdir -p $projectpath

elif [ "$1" = "addtime" ]; then

    timepath="$TODODIR/times/$2"

    # Make sure $2 doesn't exist
    if [ -e $timepath ]; then
        echo "'$2' already exists"
        exit 1
    fi

    mkdir -p $timepath

elif [ "$1" = "hide" ]; then

    taskpath="$TODODIR/tasks/$2"
    taskdir=$(dirname $taskpath)
    taskname=$(basename $taskpath)

    # Make sure $2 exists
    if [ ! -e $taskpath ]; then
        echo "'$2' does not exist"
        exit 1
    fi

    find -L "$TODODIR/times" -samefile $taskpath -delete
    mv $taskpath "$taskdir/.$taskname"

elif [ "$1" = "rm" ]; then

    taskpath="$TODODIR/tasks/$2"

    # Make sure $2 exists
    if [ ! -f $taskpath ]; then
        echo "'$2' is not a file or does not exist"
        exit 1
    fi

    find -L "$TODODIR/times" -samefile $taskpath -delete
    rm $taskpath

elif [ "$1" = "rmproject" ]; then

    projectpath="$TODODIR/tasks/$2"

    # Make sure $2 exists
    if [ ! -d $projectpath ]; then
        echo "'$2' is not a directory or does not exist"
        exit 1
    fi

    rmdir $projectpath

elif [ "$1" = "rmtime" ]; then

    timepath="$TODODIR/times/$2"

    # Make sure $2 exists
    if [ ! -d $timepath ]; then
        echo "'$2' is not a directory or does not exist"
        exit 1
    fi

    rmdir $timepath

elif [ "$1" = "edit" ]; then

    if [ -f "$TODODIR/tasks/$2" ]; then
        $EDITOR "$TODODIR/tasks/$2"
    elif [ -f "$TODODIR/times/$2" ]; then
        $EDITOR "$TODODIR/times/$2"
    else
        echo "$2 is not a file"
        exit 1
    fi

elif [ "$1" = "mv" ]; then

    taskpath="$TODODIR/tasks/$2"
    taskname=$(basename $taskpath)
    newtaskpath="$TODODIR/tasks/$3/$taskname"

    # Make sure task exists
    if [ ! -e $taskpath ]; then
        echo "'$2' does not exist"
        exit 1

    # Make sure $3 is a directory
    elif [ ! -d "$TODODIR/tasks/$3" ]; then
        echo "'$3' is not a directory"
        exit 1

    fi

    find -L "$TODODIR/times" -samefile $taskpath -delete -execdir ln -s $newtaskpath \;
    mv $taskpath $newtaskpath

elif [ "$1" = "assign" ]; then

    taskpath="$TODODIR/tasks/$2"
    newtime="$TODODIR/times/$3"

    # Make sure $2 exists
    if [ ! -e $taskpath ]; then
        echo "'$2' does not exist"
        exit 1

    # Make sure $3 is a directory
    elif [ ! -d $newtime ]; then
        echo "'$3' is not a directory"
        exit 1
    fi

    find -L "$TODODIR/times" -samefile $taskpath -delete
    ln -s $taskpath $newtime"/"

elif [ "$1" = "unassign" ]; then

    taskpath="$TODODIR/tasks/$2"

    # Make sure $2 exists
    if [ ! -f $taskpath ]; then
        echo "'$2' is not a file or does not exist"
        exit 1
    fi

    find -L "$TODODIR/times" -samefile $taskpath -delete

else

    if [ -f "$TODODIR/tasks/$1" ]; then
        less "$TODODIR/tasks/$1"
    elif [ -f "$TODODIR/times/$1" ]; then
        less "$TODODIR/times/$1"
    elif [ -d "$TODODIR/tasks/$1" ]; then
        ls -1 "$TODODIR/tasks/$1/"
    elif [ -d "$TODODIR/times/$1" ]; then
        ls -1 "$TODODIR/times/$1/"
    else
        echo "$1 is not a file or directory"
        exit 1
    fi

fi
