#! /usr/bin/env sh

# Set up $EDITOR if needed

if [ -z "$EDITOR" ]; then
    EDITOR="nano"
fi

# Set up todo directory if needed

if [ -z "$TODODIR" ]; then
    TODODIR="$HOME/.todo"
fi

if [ -e "$TODODIR" ]; then
    if [ ! -d "$TODODIR" ]; then
        echo "$TODODIR is not a directory"
        exit 1
    fi
else
    mkdir -p "$TODODIR/tasks"
    mkdir -p "$TODODIR/times"
fi

# Process arguments
if [ "$#" -eq 0 ]; then

    for dir in "waiting" "today" "thisweek" "thismonth"; do
        # TODO: Skip directory if exists but empty
        if [ -d "$TODODIR/times/$dir" ]; then
            printf "\033[1m%s\033[m\n" $dir
            ls -1 "$TODODIR/times/$dir/"
            printf "\n"
        fi
    done

elif [ "$1" = "tasks" ]; then

    tree $TODODIR/tasks

elif [ "$1" = "init" ]; then

    for dir in "waiting" "today" "thisweek" "thismonth" "someday"; do
        [ -e "$TODODIR/times/$dir" ] || mkdir "$TODODIR/times/$dir"
    done

elif [ "$1" = "add" ]; then

    # Make sure $2 doesn't exist
    if [ -e "$TODODIR/tasks/$2" ]; then
        echo "'$2' already exists"
        exit 1
    else
        touch "$TODODIR/tasks/$2"
    fi

elif [ "$1" = "addproject" ]; then

    # Make sure $2 doesn't exist
    if [ -e "$TODODIR/tasks/$2" ]; then
        echo "'$2' already exists"
        exit 1
    else
        mkdir -p "$TODODIR/tasks/$2"
    fi

elif [ "$1" = "hide" ]; then

    echo "'hide' not yet implemented"
    exit 1

    # Make sure $2 exists
    if [ ! -e "$TODODIR/$2" ]; then
        echo "'$2' does not exist"
        exit 1
    #else
        # TODO: Need to move file and update symbolic links
        #find -L "$TODODIR" -samefile "$TODODIR/$2" -execdir mv '{}' '.''{}' \;
        #find -L "$TODODIR" -samefile "$TODODIR/$2" -delete
        #find -L "$TODODIR" -samefile "$TODODIR/$2" -execdir echo '{}' \;
        # -lname '$TODODIR/$2'
    fi

elif [ "$1" = "rm" ]; then

    # Make sure $2 exists
    if [ ! -f "$TODODIR/tasks/$2" ]; then
        echo "'$2' is not a file or does not exist"
        exit 1
    else
        find -L "$TODODIR/times" -samefile "$TODODIR/tasks/$2" -delete
        rm "$TODODIR/tasks/$2"
    fi

elif [ "$1" = "edit" ]; then

    if [ -f "$TODODIR/tasks/$2" ]; then
        $EDITOR "$TODODIR/tasks/$2"
    elif [ -f "$TODODIR/times/$2" ]; then
        $EDITOR "$TODODIR/times/$2"
    else
        echo "$2 is not a file"
        exit 1
    fi

elif [ "$1" = "mv" ]; then

    # Make sure $2 exists
    if [ ! -e "$TODODIR/tasks/$2" ]; then
        echo "'$2' does not exist"
        exit 1

    # Make sure $3 is a directory
    elif [ ! -d "$TODODIR/tasks/$3" ]; then
        echo "'$3' is not a directory"
        exit 1

    fi

    # TODO: Remove existing symbolic links and recreate for new location
    mv "$TODODIR/tasks/$2" "$TODODIR/tasks/$3/"

elif [ "$1" = "assign" ]; then

    # Make sure $2 exists
    if [ ! -e "$TODODIR/tasks/$2" ]; then
        echo "'$2' does not exist"
        exit 1
    # Make sure $3 is a directory
    elif [ ! -d "$TODODIR/times/$3" ]; then
        echo "'$3' is not a directory"
        exit 1
    fi

    find -L "$TODODIR/times" -samefile "$TODODIR/tasks/$2" -delete
    ln -s "$TODODIR/tasks/$2" "$TODODIR/times/$3/"

else

    if [ -f "$TODODIR/tasks/$1" ]; then
        less "$TODODIR/tasks/$1"
    elif [ -f "$TODODIR/times/$1" ]; then
        less "$TODODIR/times/$1"
    elif [ -d "$TODODIR/tasks/$1" ]; then
        ls -1 "$TODODIR/tasks/$1/"
    elif [ -d "$TODODIR/times/$1" ]; then
        ls -1 "$TODODIR/times/$1/"
    else
        echo "$1 is not a file or directory"
        exit 1
    fi

fi
